- name: Update SLES
  zypper:
    name: '*'
    state: latest
    disable_recommends: no

- name: Remove unnecessary lio-utils
  package:
    name: lio-utils
    state: absent

- name: Remove unnecessary python-rtslib
  package:
    name: python-rtslib
    state: absent

- name: Remove unnecessary old python-configshell
  package:
    name: python-configshell
    state: absent

- name: Remove old targetcli
  package:
    name: targetcli
    state: absent

- name: Install iSCSI target packages
  package:
    name: targetcli-fb
    state: present
    disable_recommends: no

- name: Install dbus-1-python
  package:
    name: dbus-1-python
    state: present
    disable_recommends: no

- name: Start and enable targetcli service
  service: name=targetcli enabled=yes state=started

- name: Get disk with correct disk-id
  shell: ls -l /dev/disk/by-id/scsi-* | grep sdc | grep scsi-3 | awk '{ print $9; }'
  register: scsi_disk_path

- name: Create a new backstore
  targetcli_backstore:
    backstore_type: block
    backstore_name: "{{ cluster_name }}"
    options: "{{ scsi_disk_path.stdout }}"
  notify:
    - save targetcli configuration

- name: Create iscsi object
  targetcli_iscsi:
    wwn: "{{ iscsi_object }}.{{ cluster_name }}.local:{{ cluster_name }}"
  notify:
    - save targetcli configuration

- name: Add lun to iscsi object
  targetcli_iscsi_lun:
    wwn: "{{ iscsi_object }}.{{ cluster_name }}.local:{{ cluster_name }}"
    backstore_type: block
    backstore_name: "{{ cluster_name }}"
  notify:
    - save targetcli configuration

- name: Add acl 0
  targetcli_iscsi_acl:
    wwn: "{{ iscsi_object }}.{{ cluster_name }}.local:{{ cluster_name }}"
    initiator_wwn: "{{ iscsi_object }}.prod-{{ cluster_name }}-0.local:prod-{{ cluster_name }}-0"
  notify:
    - save targetcli configuration

- name: Add acl 1
  targetcli_iscsi_acl:
    wwn: "{{ iscsi_object }}.{{ cluster_name }}.local:{{ cluster_name }}"
    initiator_wwn: "{{ iscsi_object }}.prod-{{ cluster_name }}-1.local:prod-{{ cluster_name }}-1"
  register: add_acl1
  notify:
    - save targetcli configuration
