# tasks file for infra-win-bastion
---
- name: Create Windows NSG
  azure_rm_securitygroup:
    name: "windows_bastion_nsg"
    resource_group: "{{ az_resource_group }}"
    rules:
        - name: RDP
          priority: 100
          access: "Allow"
          protocol: "Tcp"
          direction: "Inbound"
          source_port_range: "*"
          source_address_prefix: "{{ allow_ips }}"
          destination_port_range: 3389
        - name: winrm
          priority: 110
          access: "Allow"
          protocol: "Tcp"
          direction: "Inbound"
          source_port_range: "*"
          source_address_prefix: "{{ allow_ips }}"
          destination_port_range: 5986
- name: Provision PIP
  azure_rm_publicipaddress:
    name: "{{ pip_name }}"
    resource_group: "{{ az_resource_group }}"
    allocation_method: "{{ pip_allocation_type }}"
    sku: "{{ pip_sku }}"
    domain_name: "{{ domain_name }}"
  register: pip_info

- name: Provision NIC
  azure_rm_networkinterface:
    name: "{{ nic_name }}"
    resource_group: "{{ az_resource_group }}"
    virtual_network: "{{ vnet_name }}"
    subnet_name: "{{ subnet_name }}"
    security_group: "windows_bastion_nsg"
    ip_configurations:
      - name: "{{ vm_name }}-nic-configuration"
        public_ip_address_name: "{{ pip_name }}"
        private_ip_allocation_method: "{{ private_ip_allocation }}"
        private_ip_address: "{{ private_ip_address }}"
        primary: yes
- name: provision new Azure virtual host
  azure_rm_virtualmachine:
    admin_username: '{{ bastion_username_windows}}'
    admin_password: '{{pw_bastion_windows}}'
    os_type: Windows
    image:
      offer: "{{ source_image_offer }}"
      publisher: "{{ source_image_publisher }}"
      sku: "{{ source_image_sku }}"
      version: "{{ source_image_version }}"
    name: '{{ vm_name }}'
    resource_group: '{{ resource_group}}'
    network_interfaces: "{{ nic_name }}"
    state: present
    vm_size: "{{ vm_size }}"
  register: vm_creation_result

- name: create Azure vm extension to enable HTTPS WinRM listener
  azure_rm_virtualmachine_extension:
    name: winrm-extension
    resource_group: '{{az_resource_group}}'
    virtual_machine_name: '{{vm_name}}'
    publisher: Microsoft.Compute
    virtual_machine_extension_type: CustomScriptExtension
    type_handler_version: 1.9
    settings: '{"commandToExecute": "powershell.exe -ExecutionPolicy ByPass {{winrm_enable_script}}"}'
    auto_upgrade_minor_version: true

- name: wait for the WinRM port to come online
  wait_for:
    port: 5986
    host: '{{azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}'
    timeout: 600

- name: Add this VM to the Ansible hosts
  add_host:
    name: "{{ vm_name }}"
    ansible_ssh_host: "{{ vm_creation_result.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    ansible_user: "{{ bastion_username_windows }}"
    ansible_password: "{{ pw_bastion_windows }}"
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    private_ip: "{{ vm_creation_result.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.privateIPAddress }}"
    public_ip: "{{ vm_creation_result.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    groups: "win_bastion"
